config/routes.rb
Pgpa::Application.routes.draw do
  root to: 'homes#show'

  resource :session, only: [:new, :destroy] do
    resources :by_keys, only: [:create]
    resources :by_totps, only: [:create]
    resources :by_passphrases, only: [:create]
  end

  resources :users, only: [:new, :index, :show]
  resource :user, only: [] do
    resources :keys, only: [:create]
    resources :totps, only: [:create]
    resources :passphrases, only: [:create]
  end

  resources :completers, only: [:show]
end

app/models/key.rb
require 'hkp'

class Key < ActiveRecord::Base
  belongs_to :user
  has_many :uids

  def update_uids!
    update_key!
    parsed_uids.each do |parsed_uid|
      uids.create_or_update!(parsed_uid)
    end
  end

  def public_key
    ctx.keys.detect {|key| key.sha == keyid }
  end

  private

  def update_key!
    raw_pub_key = hkp.fetch(keyid)
    GPGME::Key.import(raw_pub_key)
    update!(raw: raw_pub_key)
  end

  def parsed_uids
    public_key.uids
  end

  def ctx
    GPGME::Ctx.new
  end

  def hkp
    Hkp.new
  end
end

app/models/uid.rb
require 'securerandom'
require 'openssl'

class Uid < ActiveRecord::Base
  belongs_to :key
  belongs_to :user

  before_create :set_secret_key

  validates :email, uniqueness: { scope: [:user_id, :key_id] }

  def self.create_or_update!(parsed_uid)
    uid = find_or_create_by(
      email: parsed_uid.email,
      name: parsed_uid.name,
    )
    uid.update!(revoked: parsed_uid.revoked?)
    uid
  end

  def begin_auth
    update!(secret: generate_secret)

    EncryptedMailer.auth(
      email: email,
      name: name,
      secret: secret,
      public_key: key.public_key
    ).deliver
  end

  def revoke_secret!
    update!(secret: nil, checked: true)
  end

  def verified_totp?(totp)
    verifier.verify(totp)
  end

  def verified_passphrase?(phrase)
    hash_passphrase(phrase) == self.hashed_passphrase
  end

  def secret_key_uri
    verifier.provisioning_uri("pgpa - #{self.email}")
  end

  def passphrase=(s)
    self.salt = generate_salt
    self.hashed_passphrase = hash_passphrase(s)
  end

  private

  def generate_secret
    key.keyid + SecureRandom.urlsafe_base64(32)
  end

  def generate_salt
    SecureRandom.hex(64).encode('UTF-8')
  end

  def set_secret_key
    self.secret_key = ROTP::Base32.random_base32
  end

  def hash_passphrase(s)
    cipher = OpenSSL::Cipher::BF.new('CBC')
    cipher.encrypt
    cipher.key = Digest::SHA256.digest(salt)
    cipher.update("--#{self.salt}--#{s}--")
    CGI::escape(cipher.final)
  end

  def verifier
    ROTP::TOTP.new(secret_key)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :keys
  has_many :uids

  accepts_nested_attributes_for :keys
  accepts_nested_attributes_for :uids

  def self.find_by_secret(secret)
    uid = Uid.where(secret: secret).first
    if uid
      uid.revoke_secret!
      uid.key.user
    end
  end

  def begin_auth
    update_uids!
    uids.each(&:begin_auth)
  end

  private

  def update_uids!
    keys.each(&:update_uids!)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/by_keys_controller.rb
class ByKeysController < ApplicationController
  def create
    @uid = Uid.find_by_email(params[:session][:email])
    if @uid
      @uid.begin_auth
    else
      @uid.errors.add(:email, 'no such uid')
      render 'sessions/new'
    end
  end
end

app/controllers/by_passphrases_controller.rb
class ByPassphrasesController < ApplicationController
  def create
    @uid = Uid.find_by_email(params[:session][:email])
    if @uid && @uid.verified_passphrase?(params[:session][:passphrase])
      session[:user_id] = @uid.user.id
      redirect_to @uid.user
    else
      @uid.errors.add('invalid email or passphrase')
      render 'sessions/new'
    end
  end
end

app/controllers/by_totps_controller.rb
class ByTotpsController < ApplicationController
  def create
    @uid = Uid.find_by_email(params[:session][:email])
    if @uid && @uid.verified_totp?(params[:session][:totp])
      session[:user_id] = @uid.user.id
      redirect_to @uid.user
    else
      @uid.errors.add('invalid email or one-time password')
      render 'sessions/new'
    end
  end
end

app/controllers/completers_controller.rb
class CompletersController < ApplicationController
  def show
    user = User.find_by_secret(params[:id])
    if user
      sign_in(user)
      redirect_to user
    else
      redirect_to new_session_path, error: 'Invalid URL'
    end
  end

  private

  def sign_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      @user.begin_auth
    else
      render 'users/new'
    end
  end

  private

  def user_params
    params.require(:user).permit(keys_attributes: [ :keyid ])
  end
end

app/controllers/passphrases_controller.rb
class PassphrasesController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'users/new'
    end
  end

  private

  def user_params
    params.require(:user).permit(uids_attributes: [ :email, :passphrase ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/totps_controller.rb
class TotpsController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      @uid = @user.uids.last
      render
    else
      render 'users/new'
    end
  end

  private

  def user_params
    params.require(:user).permit(uids_attributes: [ :email ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.keys.build
    @user.uids.build
  end

  def show
    @user = current_user
  end

  private

  def current_user
    User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/by_keys/create.html.erb
<p>You have been sent an email with the sign in link.</p>

app/views/homes/show.html.erb
<ul>
  <li><%= link_to 'Sign in', new_session_path %></li>
  <li><%= link_to 'Sign up', new_user_path %></li>
</ul>

app/views/keys/create.html.erb
<p>You will receive an email at the specified email address. This email
is encrypted and can only be decrypted by the person with the private
key for the specified email address. Follow the link inside the email in
order to sign in.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pgpa</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/totps/create.html.erb
<p>Scan this using your <abbr title="Time-based One-time Password">TOTP</abbr> program:</p>

<p><img src="http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=<%= CGI::escape(@uid.secret_key_uri) %>"></p>

<p>Alternatively, manually enter the secret key:<p>

<pre><%= @uid.secret_key %></pre>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.primary_uid, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>With PGP key</h2>
<%= form_for @user, url: user_keys_path do |form| %>
  <%= form.fields_for :keys do |keys_form| %>
    <%= keys_form.label :keyid %>
    <%= keys_form.text_field :keyid %>
  <% end %>
  <%= form.submit 'Sign up' %>
<% end %>

<h2>With time-based one-time password</h2>
<%= form_for @user, url: user_totps_path do |form| %>
  <%= form.fields_for :uids do |uids_form| %>
    <%= uids_form.label :email %>
    <%= uids_form.text_field :email %>
  <% end %>
  <%= form.submit 'Sign up' %>
<% end %>

<h2>With an insecure memorized passphrase</h2>
<%= form_for @user, url: user_passphrases_path do |form| %>
  <%= form.fields_for :uids do |uids_form| %>
    <%= uids_form.label :email %>
    <%= uids_form.text_field :email %>
    <p class="insecure-passphrase-placeholder" data-id="user_uids_attributes_0_passphrase" data-name="user[uids_attributes][0][passphrase]">
      Your passphrase prompt will be here. It is rendered by JavaScript,
      and encrypted in JavaScript before being sent to us. This requires
      the DOMCrypt extension. We never want to see your passphrase.
    </p>
  <% end %>
  <%= form.submit 'Sign up' %>
<% end %>

app/views/users/show.html.erb
<%= debug @user %>